packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  dprint: true
  esbuild: true
  svelte-preprocess: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - dprint
  - esbuild
  - svelte-preprocess
  - unrs-resolver

patchedDependencies:
  tiddlywiki-plugin-dev@0.5.12: patches/tiddlywiki-plugin-dev@0.5.12.patch
